name: Flowzone

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - "main"
      - "master"

jobs:
  flowzone:
    name: Flowzone
    uses: product-os/flowzone/.github/workflows/flowzone.yml@master
    secrets: inherit
    with:
      balena_slugs: 'balenalabs/dbus,balenalabs/dbus-aarch64,balenalabs/dbus-amd64,balenalabs/dbus-armv7hf,balenalabs/dbus-rpi'
